### ISSUE TITLE
Cannot connect Kyma instance in WordPress setting page

### ISSUE THREAD

**Issue by ghost** [kyma-incubator/wordpress-connector#3]
Dear colleagues:

I have created a new application in my Kyma instance with status "Serving":

![image](https://user-images.githubusercontent.com/5669954/61438731-b6d09680-a972-11e9-9070-14345fc1a310.png)

Here is its application connection url:
![image](https://user-images.githubusercontent.com/5669954/61438810-e4b5db00-a972-11e9-98fd-86ea4c0054a6.png)

https://connector-service.giga.cluster.extend.cx.cloud.sap/v1/applications/signingRequests/info?token=Gz0oKfRjg7m1BdQZIspQOyWZlY6Ghfq-dfvjo14Qqt0gi-CkniprBamRoWKWRhhzlRd1ieOUeY-QXjGcorkiVw==

I paste it into Wordpress setting page and press connect button, unfortunately ended up with error message: Could not retrieve CSR info

![image](https://user-images.githubusercontent.com/5669954/61438896-0c0ca800-a973-11e9-95eb-4d75793ec851.png)

can you please kindly help? 

thanks a lot!

Best Regards,
Jerry

**Comment by ghost** [comment]
I am debugging the Kyma connector source code in Visual studio code. I have found the source code where the error is raised, however don't know what action is needed to fix them...

Your kind guidance is highly appreciated in advance!

![image](https://user-images.githubusercontent.com/5669954/61440341-d6b58980-a975-11e9-80e8-22d74b0a2650.png)

![image](https://user-images.githubusercontent.com/5669954/61440330-d2896c00-a975-11e9-870a-0ea63e290226.png)

Best regards,
Jerry

**Comment by abrain** [comment]
Hi Jerry,

did you use the 'Copy to clipboard' button to copy the URL? I believe there has been an issue with copying it directly from the textarea.

Furthermore, as a hint, the connection URL is only valid for a short period of time. The one you posted above, expired already, so I can't test with that one. You would need to acquire a new one for your next attempt.

**Comment by ghost** [comment]
Hi Abrain,

I have already discussed this issue with Piotr and now this issue is resolved. I use a fresh new token and it works.

Best Regards,
Jerry

**Comment by abrain** [comment]
Hi Jerry,
great to hear. Then I'll close the issue.
Cheers,
Andreas
